CCS Spectrometer C# Example of Absorption Measurement
Thorlabs/Light_Analysis_Examples pull request #5
Opened 2023-02-15 06:18 UTC by ZiyingZhang313

I've added the CCS spectrometer C# example of Absorption measurement. Could you please kindly review this and pull this if it works well? Thanks so much!

Best Regards
Zoe Zhang

2023-03-01 13:02 UTC, manzelmi-thorlabs requested changes

2023-03-01 13:02 UTC, manzelmi-thorlabs commented on C sharp/Thorlabs CCS Spectrometers/CCS - Absorption Measurement/CCS - Absorption Measurement/Program.cs
> +        private void ChartOD(double[] DataIntensity, double[] DataWavelength)
Can we change the name of this to ShowODChart?

2023-03-01 13:02 UTC, manzelmi-thorlabs commented on C sharp/Thorlabs CCS Spectrometers/CCS - Absorption Measurement/CCS - Absorption Measurement/Program.cs
> +﻿using System;
The code looks great. We might need to make a few changes to method names to make them more clear. We should also update the readme to include a description of the new example

2023-03-15 11:57 UTC, manzelmi-thorlabs approved these changes
Looks  great!

2023-03-15 12:34 UTC, wskopalik approved these changes
Looks good!

2023-05-16 17:52 UTC, merged